### ISSUE TITLE
Some emoji do not render

### ISSUE THREAD

**Issue by FredHappyface** [markdown-it/markdown-it-emoji#37] opened 2020-04-08 20:47 UTC
Thanks for this invaluable project 😁

The following emoji codes (supported by GitHub) are not replaced with emoji

:u6708: | u6708 
:u6709: | u6709 
:u6307: | u6307 
:u5272: | u5272 
:u7121: | u7121 
:u7981: | u7981 
:u7533: | u7533 
:u5408: | u5408 
:u7a7a: | u7a7a 
:u55b6: | u55b6

**Comment by puzrin** [comment] 2020-04-08 20:49
dupe of #33

**Closed by puzrin** 2020-04-08 20:49 UTC
